image: python:3.10

do_build:
  stage: build
  tags:
    - ml-code
  script:
    - echo "$CI_SERVER_URL is the url"
    - pip install wheel
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel
    - pip install .
  artifacts:
    paths:
      - dist/

do_deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload dist/* --repository-url http://localhost/projects/$CI_PROJECT_ID/packages/pypi --username $PACKAGE_REGISTRY_USERNAME --password $PACKAGE_REGISTRY_PASSWORD
  only:
    - main
  tags:
    - ml-code