image: python:3.10

.phx-job:
  cache:
    key: phx  # Use a unique key for each branch or tag
    paths:
      - phx
  tags:
    - ml-code
  only:
    - main
  before_script:
    - python3 -m venv phx || true
    - source phx/bin/activate
    - echo "$CI_SERVER_URL is the url"


do_build:
  extends: .phx-job
  stage: build
  script:
    - pip install wheel
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel
    - pip install .
  artifacts:
    paths:
      - dist/

do_deploy:
  extends: .phx-job
  stage: deploy
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine upload --repository-url $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi dist/*