image: python:3.9

do_build:
  stage: build
  tags:
    - ml-code
  script:
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/

do_deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload dist/* --repository-url $REPO_URI --username $PACKAGE_REGISTRY_USERNAME --password $PACKAGE_REGISTRY_PASSWORD
  only:
    - main
  tags:
    - ml-code