version: '3'

services:
  local-registry:
    image: registry:2
    ports:
      - "5001:5000"
    volumes:
      - ./.images:/var/lib/registry
    restart: unless-stopped

volumes:
  registry-data: {}
